### ISSUE TITLE
Hardcoded use of term "Scope"

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#13]
https://github.com/Natixar/natixar-frontend/blame/ef02efb304be15fcc3db79dec95d395414c956e3/src/pages/natixar/ClimateChangePage.tsx#L87

BEGESv5 no longer uses the term "scope" to reference to level groups of categories. There are 6 of them and they just have names.
This error is generic is that the term "scope" and the plural "scopes", with or without capitalization shall not be present in the front-end source code.

The generic term shall be "Groups", and "Scope 1", "Scope 2" and "Scope 3" are data returned by the back end when the selected taxonomy is GHG Protocol or Beges. Other terms are used when the selected taxonomy is BEGESv5.

**Comment by astowny** [comment]
If this is BEGESv5, we put "Groups 1", "Groups 2", "Groups 3" ... else we put "Scope" instead of "Groups"

**Comment by lepeuvedic** [comment]
You should NEVER have to guess that. The correct term is ALWAYS present in the corresponding categories hierarchy, at level 2 (level 1 being the name of the hierarchy itself). 
What you MIGHT need, is a way to detect when the name is too long to display, and in general you need a feature that intelligently shortens category names. Most are very long, but truncating the end makes no sense since it's where all the information is concentrated.
The beginning "Emissions ... " has no informational value. If the name begins like that, it can be truncated in priority. The last word is often the only difference with a neighboring category and must be preserved.
Similarly, I can guarantee that future backend version will always send L1 all alternate taxonomies, even if the rest is omitted since it's not used. The front-end code SHOULD NOT need hardcoded values and SHOULD NOT be limited to the current three taxonomies.

**Comment by ChrisNatixar** [comment]
Already fixed, BegesV5 shows the category names taken from the data returned by the back-end.
