### ISSUE TITLE
Hardcoded data on factories

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#14]
https://github.com/Natixar/natixar-frontend/blob/1b2d3c57f574d5df3aeb3f2e2d580c9bc3107637/src/pages/natixar/ContributorsPage/index.tsx#L14

Data must be retrieved from the backend, not hardcoded in the frontend.

**Comment by astowny** [comment]
Bonjour Jean-Marc,
Pour la page /contributors/scope-details/34
Quelle est la source de données pour afficher le détail dans cette page ?

**Comment by lepeuvedic** [comment]
Probably hard to solve before we correctly handle graph contexts in the front end.
The whole concept probably breaks down if you expect to have one redux store area per chart, because the backend cannot really synthesize the data. It only computes the start and end slots according to the time scale, but the amount of data transferred is basically the same. The compressed data point format is as efficient when the time step is big or small, but the back end transfers all the other dimensions verbatim, and that means that even for a simple chart (year trend for a location), a lot a data reduction is needed and a lot of useless data is transferred (all the data related to other locations). 

The design target is to manage one or more data cubes in the front-end, and to dynamically filter and slice them as needed without further request to the back-end. Several data cubes might be kept in memory at the same time only for the purpose of comparing with the previous year or similar purposes. Because the historical data does not change, the front-end should never throw away data that is still valid. When it switches to the new Scenario endpoint for data, the front-end will benefit from HTTP level optimisations  in that respect (headers like If-modified and Range).
