### ISSUE TITLE
Top Level Groups of Categories not Listed

### ISSUE THREAD

**Issue by lepeuvedic** [Natixar/natixar-frontend#61]
## Problem
Top level groups of category not listed correctly as <NatixarExpandableBar> objects in BEGESv5 mode. Only two are listed and the appearance is blocky and problematic. The behavior could be explained by an error in the data (see the backend folder and emissions file), or a bug in the algorithm (likely).
![Missing scopes on BEGESv5](https://github.com/Natixar/natixar-frontend/assets/26287656/dd9e1d58-c42a-4b3a-babe-95fd822a9bda)
If necessary, the data can be checked in the backend/src/sampleEmissions.js (samples folder as well for pure JSON). 

## Steps to Reproduce:

1. Authenticate and enter the Dashboard
2. Switch to BEGESv5 représentation mode
3. Observe that only two <NatixarExpandableBar> objects are shown, deformed, instead of 6 expected

## Desired Behavior
The donut card must display the 6 direct children of "BEGES v5", together with the total emissions of each group of categories.

**Comment by astowny** [comment]
![image](https://github.com/Natixar/natixar-frontend/assets/24301264/572942b6-e305-4cd3-8c5b-32baec804eac)

While receiving data I see no era set on the scopes while the algorithm is based on the era to genereate the rows.

**Comment by astowny** [comment]
If we use the code, we obtains this : 
![image](https://github.com/Natixar/natixar-frontend/assets/24301264/21aa9ff1-9061-4e35-bc9e-46783e071363)

because the color is set in function of the era.

**Comment by astowny** [comment]
@lepeuvedic est-ce que ce fix est correct et je peux le merge dans dev ?

**Comment by lepeuvedic-natixar** [comment]
Non, bien sûr! Même dans BEGES il n'y a pas de bijection entre scope et era. C'est donc probablement un hasard que les secteurs du donut soient de couleur différente.

Ce dont on a besoin c'est que les secteurs du donut représentent les 3 ou 6 groupes de haut niveau et que les couleurs tiennent lieu de légende, comme dans un bon vieux pie chart ordinaire.

Presque toutes les utilisations de "era" dans le code sont des bugs. C'est au mieux un filtre. Le seul endroit où il devait être utilisé est comme filtre sur la carte.
Par contre l'absence de filtre hiérarchique par catégorie me semble un manque criant qui est mal comblé par le filtre scope.

**Comment by lepeuvedic-natixar** [comment]
Ca n'explique pas pourquoi la même donnée, dans une catégorie très similaire avec le même code "era", ne donne pas la même couleur. Mais il vaut mieux attendre. J'ai une modif en cours sur ce back-end qui corrige certains index.

**Comment by lepeuvedic-natixar** [comment]
In the current state of the code, there is no provision to keep some level of continuity in the colors when switching from BEGES to BEGESv5 ?
Some groups cannot have a definite era, because they group things belonging to different eras, like upstream and downstream transportation (group 3 of BEGESv5, or scope 3 in GHG Protocol and BEGES).
BEGESv5 has a garbage category 6-1, that is intrinsically undefined in terms of era (not "O").

**Comment by lepeuvedic-natixar** [comment]
What I have in mind is, that since we have a function which returns a color as a function of category attributes, we might have a range of colors for era "O" (at last two shades of the same tint) another for the era "D" (same) and another for the era "U" (same) and a last one for mixed categories (usually U/D but could be own in some cases (transportation).  This solution would have the advantage of giving always the same tint to similar data, irrespective of the category groups.

**Comment by astowny** [comment]
Ok, and how do we manage the BEGESv5 as that is intrinsically undefined in terms of era ?

**Comment by lepeuvedic-natixar** [comment]
Good enough for a merge.
There are 4 possibilities for era: "U"/"O"/"D" and "" (empty string). I made sure it's always defined but we will keep the code that equates undefined to "".
Further work will be done in issue #5, which is about the donut and colors.
